---
server:
  port: 8889

logging.level:
  org.springframework.security: DEBUG

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: ${authDomain}/token_keys

ssoServiceUrl: ${authDomain}